import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faAngleDown,
  faAngleUp,
  faArrowDown,
  faArrowUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleArrowUp,
  faClipboard,
  faClipboardCheck,
  faClipboardList,
  faCode,
  faCog,
  faCopy,
  faDownload,
  faEdit,
  faEye,
  faFileCode,
  faFileImport,
  faFileLines,
  faFileText,
  faGear,
  faImage,
  faInfoCircle,
  faLink,
  faLock,
  faLockOpen,
  faPlus,
  faRotateLeft,
  faScrewdriverWrench,
  faSearch,
  faSpinner,
  faTableCells,
  faTextWidth,
  faThumbtack,
  faTimes,
  faTrash,
  faTriangleExclamation,
  faUpload,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

const navigationIcons = [
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChevronDown,
  faAngleUp,
  faAngleDown,
  faArrowUp,
  faArrowDown,
  faCircleArrowUp,
];
const fileIcons = [faFileImport, faDownload, faUpload, faFileCode, faFileText, faFileLines];
const clipboardIcons = [faClipboard, faCopy, faClipboardList, faClipboardCheck];
const editingIcons = [
  faEdit,
  faPlus,
  faTrash,
  faSearch,
  faXmark,
  faTimes,
  faRotateLeft,
  faThumbtack,
  faTextWidth,
];
const contentIcons = [faEye, faCode, faImage, faLink, faTableCells];
const statusIcons = [
  faCog,
  faGear,
  faLock,
  faLockOpen,
  faScrewdriverWrench,
  faSpinner,
  faCircle,
  faInfoCircle,
  faTriangleExclamation,
];

library.add(
  ...navigationIcons,
  ...fileIcons,
  ...clipboardIcons,
  ...editingIcons,
  ...contentIcons,
  ...statusIcons
);
