import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faCog,
  faLock,
  faEdit,
  faPlus,
  faTrash,
  faSearch,
  faUserCog,
  faLockOpen,
  faClipboard,
  faSignOutAlt,
  faClipboardList,
  faFileImport,
  faAngleUp,
  faAngleDown,
  faCheckSquare,
  faDownload,
  faPaperclip,
  faWrench,
  faFileCode,
  faScrewdriverWrench,
  faClipboardCheck,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faCog,
  faLock,
  faEdit,
  faPlus,
  faTrash,
  faSearch,
  faUserCog,
  faLockOpen,
  faClipboard,
  faCheckSquare,
  faSignOutAlt,
  faClipboardList,
  faClipboardCheck,
  faFileImport,
  faAngleUp,
  faAngleDown,
  faDownload,
  faPaperclip,
  faWrench,
  faFileCode,
  faScrewdriverWrench
);
