import '@testing-library/jest-dom/vitest';
import { vi } from 'vitest';

// Mock matchMedia for jsdom
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: vi.fn().mockImplementation((query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: vi.fn(),
    removeListener: vi.fn(),
    addEventListener: vi.fn(),
    removeEventListener: vi.fn(),
    dispatchEvent: vi.fn(),
  })),
});

// Mock window.api for renderer tests
const createMockApi = () => ({
  platform: 'win32' as NodeJS.Platform,
  arch: 'x64',
  storageGetSettings: vi.fn().mockResolvedValue({
    maxClips: 100,
    startMinimized: false,
    autoStart: false,
    theme: 'system',
    windowTransparency: 0,
    transparencyEnabled: false,
    opaqueWhenFocused: true,
    alwaysOnTop: false,
    rememberWindowPosition: true,
    showNotifications: false,
    codeDetectionEnabled: true,
  }),
  storageSaveSettings: vi.fn().mockResolvedValue(undefined),
  settingsChanged: vi.fn().mockResolvedValue({ ok: true, failed: [] }),
  getAutoStartState: vi.fn().mockResolvedValue(null),
  onSettingsUpdated: vi.fn().mockReturnValue(() => {}),
  hotkeysGetDefaults: vi.fn().mockResolvedValue({
    enabled: false,
    focusWindow: { enabled: true, key: 'CommandOrControl+Shift+V' },
    quickClip1: { enabled: true, key: 'CommandOrControl+Shift+1' },
    quickClip2: { enabled: true, key: 'CommandOrControl+Shift+2' },
    quickClip3: { enabled: true, key: 'CommandOrControl+Shift+3' },
    quickClip4: { enabled: true, key: 'CommandOrControl+Shift+4' },
    quickClip5: { enabled: true, key: 'CommandOrControl+Shift+5' },
    quickLook: { enabled: true, key: 'CommandOrControl+Shift+T' },
    searchClips: { enabled: true, key: 'CommandOrControl+Shift+F' },
  }),
  restartApp: vi.fn().mockResolvedValue(undefined),
  openAppPath: vi.fn().mockResolvedValue(''),
  storageGetStats: vi.fn().mockResolvedValue({ clipCount: 0, lockedCount: 0, dataSize: 0 }),
  storageExportData: vi.fn().mockResolvedValue('{}'),
  storageImportData: vi.fn().mockResolvedValue(true),
  storageClearAll: vi.fn().mockResolvedValue(true),
  searchTermsGetAll: vi.fn().mockResolvedValue([]),
  searchTermsCreate: vi.fn().mockResolvedValue(undefined),
  searchTermsUpdate: vi.fn().mockResolvedValue(undefined),
  searchTermsDelete: vi.fn().mockResolvedValue(undefined),
  quickToolsGetAll: vi.fn().mockResolvedValue([]),
  quickToolsCreate: vi.fn().mockResolvedValue(undefined),
  quickToolsUpdate: vi.fn().mockResolvedValue(undefined),
  quickToolsDelete: vi.fn().mockResolvedValue(undefined),
  templatesGetAll: vi.fn().mockResolvedValue([]),
  templatesCreate: vi.fn().mockResolvedValue(undefined),
  templatesUpdate: vi.fn().mockResolvedValue(undefined),
  templatesDelete: vi.fn().mockResolvedValue(undefined),
  groupColoursGet: vi.fn().mockResolvedValue({}),
  groupColoursSet: vi.fn().mockResolvedValue({}),
  quickClipsExportConfig: vi.fn().mockResolvedValue({
    searchTerms: [],
    tools: [],
    templates: [],
    groupColours: {},
    version: '2.0.0',
  }),
  quickClipsImportConfig: vi.fn().mockResolvedValue(undefined),
  onQuickClipsConfigChanged: vi.fn().mockReturnValue(() => {}),
  onToggleSearch: vi.fn().mockReturnValue(() => {}),
  onOpenQuickLook: vi.fn().mockReturnValue(() => {}),
  onClipboardChanged: vi.fn().mockReturnValue(() => {}),
  onHotkeyClipCopied: vi.fn().mockReturnValue(() => {}),
  onStorageReady: vi.fn().mockReturnValue(() => {}),
  startClipboardMonitoring: vi.fn().mockResolvedValue(true),
  stopClipboardMonitoring: vi.fn().mockResolvedValue(true),
  getCurrentClipboardData: vi.fn().mockResolvedValue(null),
  storageGetClipsSnapshot: vi.fn().mockResolvedValue({
    loadState: { complete: true, error: null, recoverable: false },
    clips: [],
  }),
  storageSaveClips: vi.fn().mockResolvedValue(true),
  setClipboardText: vi.fn().mockResolvedValue(undefined),
  setClipboardHTML: vi.fn().mockResolvedValue(undefined),
  setClipboardRTF: vi.fn().mockResolvedValue(undefined),
  setClipboardImage: vi.fn().mockResolvedValue(undefined),
  setClipboardBookmark: vi.fn().mockResolvedValue(undefined),
  getFullImage: vi.fn().mockResolvedValue(null),
  htmlSanitize: vi.fn().mockResolvedValue({ html: '', removed: {} }),
  openExternalUrls: vi.fn().mockResolvedValue(0),
  openSettings: vi.fn().mockResolvedValue(undefined),
  getUpdateState: vi.fn().mockResolvedValue({ status: 'idle' }),
  onUpdateState: vi.fn().mockReturnValue(() => {}),
  checkForUpdates: vi.fn().mockResolvedValue(null),
  downloadUpdate: vi.fn().mockResolvedValue(null),
  quitAndInstall: vi.fn().mockResolvedValue(undefined),
});

Object.defineProperty(window, 'api', {
  value: createMockApi(),
  writable: true,
});
