# This workflow handles PR validation only
name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  # Validate PRs (typecheck, lint, version bump check)
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for version checking

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

      - name: Run linting
        run: npm run lint

      - name: Check version bump
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version in package.json: $CURRENT_VERSION"

          # Check if tag already exists
          if git tag -l | grep -q "^v$CURRENT_VERSION$"; then
            echo "❌ Error: Tag v$CURRENT_VERSION already exists!"
            echo "Please bump the version in package.json before merging."
            exit 1
          else
            echo "✅ Version v$CURRENT_VERSION is new and valid."
          fi
