# This workflow handles manual releases when tags are pushed directly
name: Manual Tag Release

on:
  push:
    tags: ['v*']

jobs:
  # Build and create draft release when tag is pushed manually
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: mac

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Linux specific setup for AppImage and snap
      - name: Install Linux dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Always create release for tags, but as draft
          release: true

          build_script_name: build
          max_attempts: 3
        env:
          # Skip macOS code signing and notarization for now
          CSC_IDENTITY_AUTO_DISCOVERY: false
          CSC_LINK: ''
          CSC_KEY_PASSWORD: ''
